// Code generated for GNU/Hurd from glibc 2.43 headers. DO NOT EDIT.

//go:build hurd && 386

package syscall

const (
	AF_ALG                           = 0x26
	AF_APPLETALK                     = _AF_APPLETALK
	AF_ASH                           = 0x12
	AF_ATMPVC                        = 0x8
	AF_ATMSVC                        = 0x14
	AF_AX25                          = 0x3
	AF_BLUETOOTH                     = 0x1f
	AF_BRIDGE                        = 0x7
	AF_CAIF                          = 0x25
	AF_CAN                           = 0x1d
	AF_DECnet                        = _AF_DECnet
	AF_ECONET                        = 0x13
	AF_FILE                          = _AF_FILE
	AF_IEEE802154                    = 0x24
	AF_INET                          = _AF_INET
	AF_INET6                         = _AF_INET6
	AF_IPX                           = _AF_IPX
	AF_IRDA                          = 0x17
	AF_ISDN                          = 0x22
	AF_IUCV                          = 0x20
	AF_KEY                           = 0xf
	AF_LLC                           = 0x1a
	AF_LOCAL                         = _AF_LOCAL
	AF_MAX                           = _AF_MAX
	AF_NETBEUI                       = 0xd
	AF_NETLINK                       = 0x10
	AF_NETROM                        = 0x6
	AF_PACKET                        = 0x11
	AF_PHONET                        = 0x23
	AF_PPPOX                         = 0x18
	AF_RDS                           = 0x15
	AF_ROSE                          = 0xb
	AF_ROUTE                         = 0x10
	AF_RXRPC                         = 0x21
	AF_SECURITY                      = 0xe
	AF_SNA                           = _AF_SNA
	AF_TIPC                          = 0x1e
	AF_UNIX                          = _AF_UNIX
	AF_UNSPEC                        = _AF_UNSPEC
	AF_WANPIPE                       = 0x19
	AF_X25                           = 0x9
	ARPHRD_ADAPT                     = 0x108
	ARPHRD_APPLETLK                  = 0x8
	ARPHRD_ARCNET                    = 0x7
	ARPHRD_ASH                       = 0x30d
	ARPHRD_ATM                       = 0x13
	ARPHRD_AX25                      = 0x3
	ARPHRD_BIF                       = 0x307
	ARPHRD_CHAOS                     = 0x5
	ARPHRD_CISCO                     = 0x201
	ARPHRD_CSLIP                     = 0x101
	ARPHRD_CSLIP6                    = 0x103
	ARPHRD_DDCMP                     = 0x205
	ARPHRD_DLCI                      = 0xf
	ARPHRD_ECONET                    = 0x30e
	ARPHRD_EETHER                    = 0x2
	ARPHRD_ETHER                     = 0x1
	ARPHRD_EUI64                     = 0x1b
	ARPHRD_FCAL                      = 0x311
	ARPHRD_FCFABRIC                  = 0x313
	ARPHRD_FCPL                      = 0x312
	ARPHRD_FCPP                      = 0x310
	ARPHRD_FDDI                      = 0x306
	ARPHRD_FRAD                      = 0x302
	ARPHRD_HDLC                      = 0x201
	ARPHRD_HIPPI                     = 0x30c
	ARPHRD_HWX25                     = 0x110
	ARPHRD_IEEE1394                  = 0x18
	ARPHRD_IEEE802                   = 0x6
	ARPHRD_IEEE80211                 = 0x321
	ARPHRD_IEEE80211_PRISM           = 0x322
	ARPHRD_IEEE80211_RADIOTAP        = 0x323
	ARPHRD_IEEE802154                = 0x324
	ARPHRD_IEEE802154_PHY            = 0x325
	ARPHRD_IEEE802_TR                = 0x320
	ARPHRD_INFINIBAND                = 0x20
	ARPHRD_IPDDP                     = 0x309
	ARPHRD_IPGRE                     = 0x30a
	ARPHRD_IRDA                      = 0x30f
	ARPHRD_LAPB                      = 0x204
	ARPHRD_LOCALTLK                  = 0x305
	ARPHRD_LOOPBACK                  = 0x304
	ARPHRD_METRICOM                  = 0x17
	ARPHRD_NETROM                    = 0x0
	ARPHRD_NONE                      = 0xfffe
	ARPHRD_PIMREG                    = 0x30b
	ARPHRD_PPP                       = 0x200
	ARPHRD_PRONET                    = 0x4
	ARPHRD_RAWHDLC                   = 0x206
	ARPHRD_ROSE                      = 0x10e
	ARPHRD_RSRVD                     = 0x104
	ARPHRD_SIT                       = 0x308
	ARPHRD_SKIP                      = 0x303
	ARPHRD_SLIP                      = 0x100
	ARPHRD_SLIP6                     = 0x102
	ARPHRD_TUNNEL                    = 0x300
	ARPHRD_TUNNEL6                   = 0x301
	ARPHRD_VOID                      = 0xffff
	ARPHRD_X25                       = 0x10f
	BPF_A                            = 0x10
	BPF_ABS                          = 0x20
	BPF_ADD                          = 0x0
	BPF_ALU                          = 0x4
	BPF_AND                          = 0x50
	BPF_B                            = 0x10
	BPF_DIV                          = 0x30
	BPF_H                            = 0x8
	BPF_IMM                          = 0x0
	BPF_IND                          = 0x40
	BPF_JA                           = 0x0
	BPF_JEQ                          = 0x10
	BPF_JGE                          = 0x30
	BPF_JGT                          = 0x20
	BPF_JMP                          = 0x5
	BPF_JSET                         = 0x40
	BPF_K                            = 0x0
	BPF_LD                           = 0x0
	BPF_LDX                          = 0x1
	BPF_LEN                          = 0x80
	BPF_LSH                          = 0x60
	BPF_MAJOR_VERSION                = 0x1
	BPF_MAXINSNS                     = 0x1000
	BPF_MEM                          = 0x60
	BPF_MEMWORDS                     = 0x10
	BPF_MINOR_VERSION                = 0x1
	BPF_MISC                         = 0x7
	BPF_MSH                          = 0xa0
	BPF_MUL                          = 0x20
	BPF_NEG                          = 0x80
	BPF_OR                           = 0x40
	BPF_RET                          = 0x6
	BPF_RSH                          = 0x70
	BPF_ST                           = 0x2
	BPF_STX                          = 0x3
	BPF_SUB                          = 0x10
	BPF_TAX                          = 0x0
	BPF_TXA                          = 0x80
	BPF_W                            = 0x0
	BPF_X                            = 0x8
	DT_BLK                           = _DT_BLK
	DT_CHR                           = _DT_CHR
	DT_DIR                           = _DT_DIR
	DT_FIFO                          = _DT_FIFO
	DT_LNK                           = _DT_LNK
	DT_REG                           = _DT_REG
	DT_SOCK                          = _DT_SOCK
	DT_UNKNOWN                       = _DT_UNKNOWN
	DT_WHT                           = _DT_WHT
	EPOLLERR                         = 0x8
	EPOLLET                          = -0x80000000
	EPOLLHUP                         = 0x10
	EPOLLIN                          = 0x1
	EPOLLMSG                         = 0x400
	EPOLLONESHOT                     = 0x40000000
	EPOLLOUT                         = 0x4
	EPOLLPRI                         = 0x2
	EPOLLRDBAND                      = 0x80
	EPOLLRDHUP                       = 0x2000
	EPOLLRDNORM                      = 0x40
	EPOLLWRBAND                      = 0x200
	EPOLLWRNORM                      = 0x100
	EPOLL_CLOEXEC                    = 0x80000
	EPOLL_CTL_ADD                    = 0x1
	EPOLL_CTL_DEL                    = 0x2
	EPOLL_CTL_MOD                    = 0x3
	EPOLL_NONBLOCK                   = 0x800
	ETH_P_1588                       = 0x88f7
	ETH_P_8021Q                      = 0x8100
	ETH_P_802_2                      = 0x4
	ETH_P_802_3                      = 0x1
	ETH_P_AARP                       = 0x80f3
	ETH_P_ALL                        = 0x3
	ETH_P_AOE                        = 0x88a2
	ETH_P_ARCNET                     = 0x1a
	ETH_P_ARP                        = 0x806
	ETH_P_ATALK                      = 0x809b
	ETH_P_ATMFATE                    = 0x8884
	ETH_P_ATMMPOA                    = 0x884c
	ETH_P_AX25                       = 0x2
	ETH_P_BPQ                        = 0x8ff
	ETH_P_CAIF                       = 0xf7
	ETH_P_CAN                        = 0xc
	ETH_P_CONTROL                    = 0x16
	ETH_P_CUST                       = 0x6006
	ETH_P_DDCMP                      = 0x6
	ETH_P_DEC                        = 0x6000
	ETH_P_DIAG                       = 0x6005
	ETH_P_DNA_DL                     = 0x6001
	ETH_P_DNA_RC                     = 0x6002
	ETH_P_DNA_RT                     = 0x6003
	ETH_P_DSA                        = 0x1b
	ETH_P_ECONET                     = 0x18
	ETH_P_EDSA                       = 0xdada
	ETH_P_FCOE                       = 0x8906
	ETH_P_FIP                        = 0x8914
	ETH_P_HDLC                       = 0x19
	ETH_P_IEEE802154                 = 0xf6
	ETH_P_IEEEPUP                    = 0xa00
	ETH_P_IEEEPUPAT                  = 0xa01
	ETH_P_IP                         = 0x800
	ETH_P_IPV6                       = 0x86dd
	ETH_P_IPX                        = 0x8137
	ETH_P_IRDA                       = 0x17
	ETH_P_LAT                        = 0x6004
	ETH_P_LINK_CTL                   = 0x886c
	ETH_P_LOCALTALK                  = 0x9
	ETH_P_LOOP                       = 0x60
	ETH_P_MOBITEX                    = 0x15
	ETH_P_MPLS_MC                    = 0x8848
	ETH_P_MPLS_UC                    = 0x8847
	ETH_P_PAE                        = 0x888e
	ETH_P_PAUSE                      = 0x8808
	ETH_P_PHONET                     = 0xf5
	ETH_P_PPPTALK                    = 0x10
	ETH_P_PPP_DISC                   = 0x8863
	ETH_P_PPP_MP                     = 0x8
	ETH_P_PPP_SES                    = 0x8864
	ETH_P_PUP                        = 0x200
	ETH_P_PUPAT                      = 0x201
	ETH_P_RARP                       = 0x8035
	ETH_P_SCA                        = 0x6007
	ETH_P_SLOW                       = 0x8809
	ETH_P_SNAP                       = 0x5
	ETH_P_TEB                        = 0x6558
	ETH_P_TIPC                       = 0x88ca
	ETH_P_TRAILER                    = 0x1c
	ETH_P_TR_802_2                   = 0x11
	ETH_P_WAN_PPP                    = 0x7
	ETH_P_WCCP                       = 0x883e
	ETH_P_X25                        = 0x805
	FD_CLOEXEC                       = _FD_CLOEXEC
	FD_SETSIZE                       = _FD_SETSIZE
	F_DUPFD                          = _F_DUPFD
	F_DUPFD_CLOEXEC                  = _F_DUPFD_CLOEXEC
	F_EXLCK                          = 0x4
	F_GETFD                          = _F_GETFD
	F_GETFL                          = _F_GETFL
	F_GETLEASE                       = 0x401
	F_GETLK                          = 0xc
	F_GETLK64                        = _F_GETLK64
	F_GETOWN                         = _F_GETOWN
	F_GETOWN_EX                      = 0x10
	F_GETPIPE_SZ                     = 0x408
	F_GETSIG                         = 0xb
	F_LOCK                           = _F_LOCK
	F_NOTIFY                         = 0x402
	F_OK                             = _F_OK
	F_RDLCK                          = _F_RDLCK
	F_SETFD                          = _F_SETFD
	F_SETFL                          = _F_SETFL
	F_SETLEASE                       = 0x400
	F_SETLK                          = 0xd
	F_SETLK64                        = _F_SETLK64
	F_SETLKW                         = 0xe
	F_SETLKW64                       = _F_SETLKW64
	F_SETOWN                         = _F_SETOWN
	F_SETOWN_EX                      = 0xf
	F_SETPIPE_SZ                     = 0x407
	F_SETSIG                         = 0xa
	F_SHLCK                          = 0x8
	F_TEST                           = _F_TEST
	F_TLOCK                          = _F_TLOCK
	F_ULOCK                          = _F_ULOCK
	F_UNLCK                          = _F_UNLCK
	F_WRLCK                          = _F_WRLCK
	ICMPV6_FILTER                    = 0x1
	IFA_F_DADFAILED                  = 0x8
	IFA_F_DEPRECATED                 = 0x20
	IFA_F_HOMEADDRESS                = 0x10
	IFA_F_NODAD                      = 0x2
	IFA_F_OPTIMISTIC                 = 0x4
	IFA_F_PERMANENT                  = 0x80
	IFA_F_SECONDARY                  = 0x1
	IFA_F_TEMPORARY                  = 0x1
	IFA_F_TENTATIVE                  = 0x40
	IFA_MAX                          = 0x7
	IFF_ALLMULTI                     = _IFF_ALLMULTI
	IFF_AUTOMEDIA                    = _IFF_AUTOMEDIA
	IFF_BROADCAST                    = _IFF_BROADCAST
	IFF_DEBUG                        = _IFF_DEBUG
	IFF_DYNAMIC                      = _IFF_DYNAMIC
	IFF_LOOPBACK                     = _IFF_LOOPBACK
	IFF_MASTER                       = _IFF_MASTER
	IFF_MULTICAST                    = _IFF_MULTICAST
	IFF_NOARP                        = _IFF_NOARP
	IFF_NOTRAILERS                   = _IFF_NOTRAILERS
	IFF_NO_PI                        = 0x1000
	IFF_ONE_QUEUE                    = 0x2000
	IFF_POINTOPOINT                  = _IFF_POINTOPOINT
	IFF_PORTSEL                      = _IFF_PORTSEL
	IFF_PROMISC                      = _IFF_PROMISC
	IFF_RUNNING                      = _IFF_RUNNING
	IFF_SLAVE                        = _IFF_SLAVE
	IFF_TAP                          = 0x2
	IFF_TUN                          = 0x1
	IFF_TUN_EXCL                     = 0x8000
	IFF_UP                           = _IFF_UP
	IFF_VNET_HDR                     = 0x4000
	IFNAMSIZ                         = _IFNAMSIZ
	IN_ACCESS                        = 0x1
	IN_ALL_EVENTS                    = 0xfff
	IN_ATTRIB                        = 0x4
	IN_CLASSA_HOST                   = _IN_CLASSA_HOST
	IN_CLASSA_MAX                    = _IN_CLASSA_MAX
	IN_CLASSA_NET                    = _IN_CLASSA_NET
	IN_CLASSA_NSHIFT                 = _IN_CLASSA_NSHIFT
	IN_CLASSB_HOST                   = _IN_CLASSB_HOST
	IN_CLASSB_MAX                    = _IN_CLASSB_MAX
	IN_CLASSB_NET                    = _IN_CLASSB_NET
	IN_CLASSB_NSHIFT                 = _IN_CLASSB_NSHIFT
	IN_CLASSC_HOST                   = _IN_CLASSC_HOST
	IN_CLASSC_NET                    = _IN_CLASSC_NET
	IN_CLASSC_NSHIFT                 = _IN_CLASSC_NSHIFT
	IN_CLOEXEC                       = 0x80000
	IN_CLOSE                         = 0x18
	IN_CLOSE_NOWRITE                 = 0x10
	IN_CLOSE_WRITE                   = 0x8
	IN_CREATE                        = 0x100
	IN_DELETE                        = 0x200
	IN_DELETE_SELF                   = 0x400
	IN_DONT_FOLLOW                   = 0x2000000
	IN_EXCL_UNLINK                   = 0x4000000
	IN_IGNORED                       = 0x8000
	IN_ISDIR                         = 0x40000000
	IN_LOOPBACKNET                   = _IN_LOOPBACKNET
	IN_MASK_ADD                      = 0x20000000
	IN_MODIFY                        = 0x2
	IN_MOVE                          = 0xc0
	IN_MOVED_FROM                    = 0x40
	IN_MOVED_TO                      = 0x80
	IN_MOVE_SELF                     = 0x800
	IN_NONBLOCK                      = 0x800
	IN_ONESHOT                       = 0x80000000
	IN_ONLYDIR                       = 0x1000000
	IN_OPEN                          = 0x20
	IN_Q_OVERFLOW                    = 0x4000
	IN_UNMOUNT                       = 0x2000
	IPPROTO_AH                       = _IPPROTO_AH
	IPPROTO_COMP                     = _IPPROTO_COMP
	IPPROTO_DCCP                     = _IPPROTO_DCCP
	IPPROTO_DSTOPTS                  = _IPPROTO_DSTOPTS
	IPPROTO_EGP                      = _IPPROTO_EGP
	IPPROTO_ENCAP                    = _IPPROTO_ENCAP
	IPPROTO_ESP                      = _IPPROTO_ESP
	IPPROTO_FRAGMENT                 = _IPPROTO_FRAGMENT
	IPPROTO_GRE                      = _IPPROTO_GRE
	IPPROTO_HOPOPTS                  = _IPPROTO_HOPOPTS
	IPPROTO_ICMP                     = _IPPROTO_ICMP
	IPPROTO_ICMPV6                   = _IPPROTO_ICMPV6
	IPPROTO_IDP                      = _IPPROTO_IDP
	IPPROTO_IGMP                     = _IPPROTO_IGMP
	IPPROTO_IP                       = _IPPROTO_IP
	IPPROTO_IPIP                     = _IPPROTO_IPIP
	IPPROTO_IPV6                     = _IPPROTO_IPV6
	IPPROTO_MTP                      = _IPPROTO_MTP
	IPPROTO_NONE                     = _IPPROTO_NONE
	IPPROTO_PIM                      = _IPPROTO_PIM
	IPPROTO_PUP                      = _IPPROTO_PUP
	IPPROTO_RAW                      = _IPPROTO_RAW
	IPPROTO_ROUTING                  = _IPPROTO_ROUTING
	IPPROTO_RSVP                     = _IPPROTO_RSVP
	IPPROTO_SCTP                     = _IPPROTO_SCTP
	IPPROTO_TCP                      = _IPPROTO_TCP
	IPPROTO_TP                       = _IPPROTO_TP
	IPPROTO_UDP                      = _IPPROTO_UDP
	IPPROTO_UDPLITE                  = _IPPROTO_UDPLITE
	IPV6_2292DSTOPTS                 = _IPV6_2292DSTOPTS
	IPV6_2292HOPLIMIT                = _IPV6_2292HOPLIMIT
	IPV6_2292HOPOPTS                 = _IPV6_2292HOPOPTS
	IPV6_2292PKTINFO                 = _IPV6_2292PKTINFO
	IPV6_2292PKTOPTIONS              = _IPV6_2292PKTOPTIONS
	IPV6_2292RTHDR                   = _IPV6_2292RTHDR
	IPV6_ADDRFORM                    = _IPV6_ADDRFORM
	IPV6_ADD_MEMBERSHIP              = _IPV6_ADD_MEMBERSHIP
	IPV6_AUTHHDR                     = 0xa
	IPV6_CHECKSUM                    = _IPV6_CHECKSUM
	IPV6_DROP_MEMBERSHIP             = _IPV6_DROP_MEMBERSHIP
	IPV6_DSTOPTS                     = _IPV6_DSTOPTS
	IPV6_HOPLIMIT                    = _IPV6_HOPLIMIT
	IPV6_HOPOPTS                     = _IPV6_HOPOPTS
	IPV6_IPSEC_POLICY                = 0x22
	IPV6_JOIN_ANYCAST                = _IPV6_JOIN_ANYCAST
	IPV6_JOIN_GROUP                  = _IPV6_JOIN_GROUP
	IPV6_LEAVE_ANYCAST               = _IPV6_LEAVE_ANYCAST
	IPV6_LEAVE_GROUP                 = _IPV6_LEAVE_GROUP
	IPV6_MTU                         = _IPV6_MTU
	IPV6_MTU_DISCOVER                = _IPV6_MTU_DISCOVER
	IPV6_MULTICAST_HOPS              = _IPV6_MULTICAST_HOPS
	IPV6_MULTICAST_IF                = _IPV6_MULTICAST_IF
	IPV6_MULTICAST_LOOP              = _IPV6_MULTICAST_LOOP
	IPV6_NEXTHOP                     = 0x9
	IPV6_PKTINFO                     = _IPV6_PKTINFO
	IPV6_PMTUDISC_DO                 = _IPV6_PMTUDISC_DO
	IPV6_PMTUDISC_DONT               = _IPV6_PMTUDISC_DONT
	IPV6_PMTUDISC_PROBE              = _IPV6_PMTUDISC_PROBE
	IPV6_PMTUDISC_WANT               = _IPV6_PMTUDISC_WANT
	IPV6_RECVDSTOPTS                 = _IPV6_RECVDSTOPTS
	IPV6_RECVERR                     = _IPV6_RECVERR
	IPV6_RECVHOPLIMIT                = _IPV6_RECVHOPLIMIT
	IPV6_RECVHOPOPTS                 = _IPV6_RECVHOPOPTS
	IPV6_RECVPKTINFO                 = _IPV6_RECVPKTINFO
	IPV6_RECVRTHDR                   = _IPV6_RECVRTHDR
	IPV6_RECVTCLASS                  = _IPV6_RECVTCLASS
	IPV6_ROUTER_ALERT                = _IPV6_ROUTER_ALERT
	IPV6_RTHDR                       = _IPV6_RTHDR
	IPV6_RTHDRDSTOPTS                = _IPV6_RTHDRDSTOPTS
	IPV6_RTHDR_LOOSE                 = _IPV6_RTHDR_LOOSE
	IPV6_RTHDR_STRICT                = _IPV6_RTHDR_STRICT
	IPV6_RTHDR_TYPE_0                = _IPV6_RTHDR_TYPE_0
	IPV6_RXDSTOPTS                   = _IPV6_RXDSTOPTS
	IPV6_RXHOPOPTS                   = _IPV6_RXHOPOPTS
	IPV6_TCLASS                      = _IPV6_TCLASS
	IPV6_UNICAST_HOPS                = _IPV6_UNICAST_HOPS
	IPV6_V6ONLY                      = _IPV6_V6ONLY
	IPV6_XFRM_POLICY                 = 0x23
	IP_ADD_MEMBERSHIP                = _IP_ADD_MEMBERSHIP
	IP_ADD_SOURCE_MEMBERSHIP         = 0x27
	IP_BLOCK_SOURCE                  = 0x26
	IP_DEFAULT_MULTICAST_LOOP        = 0x1
	IP_DEFAULT_MULTICAST_TTL         = 0x1
	IP_DF                            = 0x4000
	IP_DROP_MEMBERSHIP               = _IP_DROP_MEMBERSHIP
	IP_DROP_SOURCE_MEMBERSHIP        = 0x28
	IP_FREEBIND                      = 0xf
	IP_HDRINCL                       = _IP_HDRINCL
	IP_IPSEC_POLICY                  = 0x10
	IP_MAXPACKET                     = 0xffff
	IP_MAX_MEMBERSHIPS               = 0x14
	IP_MF                            = 0x2000
	IP_MINTTL                        = 0x15
	IP_MSFILTER                      = 0x29
	IP_MSS                           = 0x240
	IP_MTU                           = 0xe
	IP_MTU_DISCOVER                  = 0xa
	IP_MULTICAST_IF                  = _IP_MULTICAST_IF
	IP_MULTICAST_LOOP                = _IP_MULTICAST_LOOP
	IP_MULTICAST_TTL                 = _IP_MULTICAST_TTL
	IP_OFFMASK                       = 0x1fff
	IP_OPTIONS                       = _IP_OPTIONS
	IP_ORIGDSTADDR                   = 0x14
	IP_PASSSEC                       = 0x12
	IP_PKTINFO                       = _IP_PKTINFO
	IP_PKTOPTIONS                    = 0x9
	IP_PMTUDISC                      = 0xa
	IP_PMTUDISC_DO                   = _IP_PMTUDISC_DO
	IP_PMTUDISC_DONT                 = _IP_PMTUDISC_DONT
	IP_PMTUDISC_PROBE                = _IP_PMTUDISC_PROBE
	IP_PMTUDISC_WANT                 = _IP_PMTUDISC_WANT
	IP_RECVERR                       = 0xb
	IP_RECVOPTS                      = _IP_RECVOPTS
	IP_RECVORIGDSTADDR               = 0x14
	IP_RECVRETOPTS                   = _IP_RECVRETOPTS
	IP_RECVTOS                       = 0xd
	IP_RECVTTL                       = 0xc
	IP_RETOPTS                       = _IP_RETOPTS
	IP_RF                            = 0x8000
	IP_ROUTER_ALERT                  = 0x5
	IP_TOS                           = _IP_TOS
	IP_TRANSPARENT                   = 0x13
	IP_TTL                           = _IP_TTL
	IP_UNBLOCK_SOURCE                = 0x25
	IP_XFRM_POLICY                   = 0x11
	LINUX_REBOOT_CMD_CAD_OFF         = 0x0
	LINUX_REBOOT_CMD_CAD_ON          = 0x89abcdef
	LINUX_REBOOT_CMD_HALT            = 0xcdef0123
	LINUX_REBOOT_CMD_KEXEC           = 0x45584543
	LINUX_REBOOT_CMD_POWER_OFF       = 0x4321fedc
	LINUX_REBOOT_CMD_RESTART         = 0x1234567
	LINUX_REBOOT_CMD_RESTART2        = 0xa1b2c3d4
	LINUX_REBOOT_CMD_SW_SUSPEND      = 0xd000fce2
	LINUX_REBOOT_MAGIC1              = 0xfee1dead
	LINUX_REBOOT_MAGIC2              = 0x28121969
	LOCK_EX                          = _LOCK_EX
	LOCK_NB                          = _LOCK_NB
	LOCK_SH                          = _LOCK_SH
	LOCK_UN                          = _LOCK_UN
	MADV_DOFORK                      = 0xb
	MADV_DONTFORK                    = 0xa
	MADV_DONTNEED                    = _MADV_DONTNEED
	MADV_HUGEPAGE                    = 0xe
	MADV_HWPOISON                    = 0x64
	MADV_MERGEABLE                   = 0xc
	MADV_NOHUGEPAGE                  = 0xf
	MADV_NORMAL                      = _MADV_NORMAL
	MADV_RANDOM                      = _MADV_RANDOM
	MADV_REMOVE                      = 0x9
	MADV_SEQUENTIAL                  = _MADV_SEQUENTIAL
	MADV_UNMERGEABLE                 = 0xd
	MADV_WILLNEED                    = _MADV_WILLNEED
	MAP_32BIT                        = _MAP_32BIT
	MAP_ANON                         = _MAP_ANON
	MAP_ANONYMOUS                    = _MAP_ANONYMOUS
	MAP_DENYWRITE                    = 0x800
	MAP_EXECUTABLE                   = 0x1000
	MAP_FILE                         = _MAP_FILE
	MAP_FIXED                        = _MAP_FIXED
	MAP_GROWSDOWN                    = 0x100
	MAP_HUGETLB                      = 0x40000
	MAP_LOCKED                       = 0x2000
	MAP_NONBLOCK                     = 0x10000
	MAP_NORESERVE                    = _MAP_NORESERVE
	MAP_POPULATE                     = 0x8000
	MAP_PRIVATE                      = _MAP_PRIVATE
	MAP_SHARED                       = _MAP_SHARED
	MAP_STACK                        = 0x20000
	MAP_TYPE                         = _MAP_TYPE
	MCL_CURRENT                      = _MCL_CURRENT
	MCL_FUTURE                       = _MCL_FUTURE
	MNT_DETACH                       = 0x2
	MNT_EXPIRE                       = 0x4
	MNT_FORCE                        = 0x1
	MSG_CMSG_CLOEXEC                 = _MSG_CMSG_CLOEXEC
	MSG_CONFIRM                      = 0x800
	MSG_CTRUNC                       = _MSG_CTRUNC
	MSG_DONTROUTE                    = _MSG_DONTROUTE
	MSG_DONTWAIT                     = _MSG_DONTWAIT
	MSG_EOR                          = _MSG_EOR
	MSG_ERRQUEUE                     = 0x2000
	MSG_FASTOPEN                     = 0x20000000
	MSG_FIN                          = 0x200
	MSG_MORE                         = 0x8000
	MSG_NOSIGNAL                     = _MSG_NOSIGNAL
	MSG_OOB                          = _MSG_OOB
	MSG_PEEK                         = _MSG_PEEK
	MSG_PROXY                        = 0x10
	MSG_RST                          = 0x1000
	MSG_SYN                          = 0x400
	MSG_TRUNC                        = _MSG_TRUNC
	MSG_TRYHARD                      = 0x4
	MSG_WAITALL                      = _MSG_WAITALL
	MSG_WAITFORONE                   = 0x10000
	MS_ACTIVE                        = 0x40000000
	MS_ASYNC                         = _MS_ASYNC
	MS_BIND                          = 0x1000
	MS_DIRSYNC                       = 0x80
	MS_INVALIDATE                    = _MS_INVALIDATE
	MS_I_VERSION                     = 0x800000
	MS_KERNMOUNT                     = 0x400000
	MS_MANDLOCK                      = 0x40
	MS_MGC_MSK                       = 0xffff0000
	MS_MGC_VAL                       = 0xc0ed0000
	MS_MOVE                          = 0x2000
	MS_NOATIME                       = 0x400
	MS_NODEV                         = 0x4
	MS_NODIRATIME                    = 0x800
	MS_NOEXEC                        = 0x8
	MS_NOSUID                        = 0x2
	MS_NOUSER                        = -0x80000000
	MS_POSIXACL                      = 0x10000
	MS_PRIVATE                       = 0x40000
	MS_RDONLY                        = 0x1
	MS_REC                           = 0x4000
	MS_RELATIME                      = 0x200000
	MS_REMOUNT                       = 0x20
	MS_RMT_MASK                      = 0x800051
	MS_SHARED                        = 0x100000
	MS_SILENT                        = 0x8000
	MS_SLAVE                         = 0x80000
	MS_STRICTATIME                   = 0x1000000
	MS_SYNC                          = _MS_SYNC
	MS_SYNCHRONOUS                   = 0x10
	MS_UNBINDABLE                    = 0x20000
	NAME_MAX                         = _NAME_MAX
	NETLINK_ADD_MEMBERSHIP           = 0x1
	NETLINK_AUDIT                    = 0x9
	NETLINK_BROADCAST_ERROR          = 0x4
	NETLINK_CONNECTOR                = 0xb
	NETLINK_DNRTMSG                  = 0xe
	NETLINK_DROP_MEMBERSHIP          = 0x2
	NETLINK_ECRYPTFS                 = 0x13
	NETLINK_FIB_LOOKUP               = 0xa
	NETLINK_FIREWALL                 = 0x3
	NETLINK_GENERIC                  = 0x10
	NETLINK_INET_DIAG                = 0x4
	NETLINK_IP6_FW                   = 0xd
	NETLINK_ISCSI                    = 0x8
	NETLINK_KOBJECT_UEVENT           = 0xf
	NETLINK_NETFILTER                = 0xc
	NETLINK_NFLOG                    = 0x5
	NETLINK_NO_ENOBUFS               = 0x5
	NETLINK_PKTINFO                  = 0x3
	NETLINK_ROUTE                    = 0x0
	NETLINK_SCSITRANSPORT            = 0x12
	NETLINK_SELINUX                  = 0x7
	NETLINK_UNUSED                   = 0x1
	NETLINK_USERSOCK                 = 0x2
	NETLINK_XFRM                     = 0x6
	NLA_ALIGNTO                      = 0x4
	NLA_F_NESTED                     = 0x8000
	NLA_F_NET_BYTEORDER              = 0x4000
	NLA_HDRLEN                       = 0x4
	NLMSG_ALIGNTO                    = 0x4
	NLMSG_DONE                       = 0x3
	NLMSG_ERROR                      = 0x2
	NLMSG_HDRLEN                     = 0x10
	NLMSG_MIN_TYPE                   = 0x10
	NLMSG_NOOP                       = 0x1
	NLMSG_OVERRUN                    = 0x4
	NLM_F_ACK                        = 0x4
	NLM_F_APPEND                     = 0x800
	NLM_F_ATOMIC                     = 0x400
	NLM_F_CREATE                     = 0x400
	NLM_F_DUMP                       = 0x300
	NLM_F_ECHO                       = 0x8
	NLM_F_EXCL                       = 0x200
	NLM_F_MATCH                      = 0x200
	NLM_F_MULTI                      = 0x2
	NLM_F_REPLACE                    = 0x100
	NLM_F_REQUEST                    = 0x1
	NLM_F_ROOT                       = 0x100
	O_ACCMODE                        = _O_ACCMODE
	O_APPEND                         = _O_APPEND
	O_ASYNC                          = _O_ASYNC
	O_CLOEXEC                        = _O_CLOEXEC
	O_CREAT                          = _O_CREAT
	O_DIRECT                         = 0x4000
	O_DIRECTORY                      = _O_DIRECTORY
	O_DSYNC                          = _O_DSYNC
	O_EXCL                           = _O_EXCL
	O_FSYNC                          = _O_FSYNC
	O_LARGEFILE                      = _O_LARGEFILE
	O_NDELAY                         = _O_NDELAY
	O_NOATIME                        = _O_NOATIME
	O_NOCTTY                         = _O_NOCTTY
	O_NOFOLLOW                       = _O_NOFOLLOW
	O_NONBLOCK                       = _O_NONBLOCK
	O_RDONLY                         = _O_RDONLY
	O_RDWR                           = _O_RDWR
	O_RSYNC                          = _O_RSYNC
	O_SYNC                           = _O_SYNC
	O_TRUNC                          = _O_TRUNC
	O_WRONLY                         = _O_WRONLY
	PACKET_ADD_MEMBERSHIP            = 0x1
	PACKET_BROADCAST                 = 0x1
	PACKET_DROP_MEMBERSHIP           = 0x2
	PACKET_FASTROUTE                 = 0x6
	PACKET_HOST                      = 0x0
	PACKET_LOOPBACK                  = 0x5
	PACKET_MR_ALLMULTI               = 0x2
	PACKET_MR_MULTICAST              = 0x0
	PACKET_MR_PROMISC                = 0x1
	PACKET_MULTICAST                 = 0x2
	PACKET_OTHERHOST                 = 0x3
	PACKET_OUTGOING                  = 0x4
	PACKET_RECV_OUTPUT               = 0x3
	PACKET_RX_RING                   = 0x5
	PACKET_STATISTICS                = 0x6
	PRIO_PGRP                        = _PRIO_PGRP
	PRIO_PROCESS                     = _PRIO_PROCESS
	PRIO_USER                        = _PRIO_USER
	PROT_EXEC                        = _PROT_EXEC
	PROT_GROWSDOWN                   = 0x1000000
	PROT_GROWSUP                     = 0x2000000
	PROT_NONE                        = _PROT_NONE
	PROT_READ                        = _PROT_READ
	PROT_WRITE                       = _PROT_WRITE
	PR_CAPBSET_DROP                  = 0x18
	PR_CAPBSET_READ                  = 0x17
	PR_ENDIAN_BIG                    = 0x0
	PR_ENDIAN_LITTLE                 = 0x1
	PR_ENDIAN_PPC_LITTLE             = 0x2
	PR_FPEMU_NOPRINT                 = 0x1
	PR_FPEMU_SIGFPE                  = 0x2
	PR_FP_EXC_ASYNC                  = 0x2
	PR_FP_EXC_DISABLED               = 0x0
	PR_FP_EXC_DIV                    = 0x10000
	PR_FP_EXC_INV                    = 0x100000
	PR_FP_EXC_NONRECOV               = 0x1
	PR_FP_EXC_OVF                    = 0x20000
	PR_FP_EXC_PRECISE                = 0x3
	PR_FP_EXC_RES                    = 0x80000
	PR_FP_EXC_SW_ENABLE              = 0x80
	PR_FP_EXC_UND                    = 0x40000
	PR_GET_DUMPABLE                  = 0x3
	PR_GET_ENDIAN                    = 0x13
	PR_GET_FPEMU                     = 0x9
	PR_GET_FPEXC                     = 0xb
	PR_GET_KEEPCAPS                  = 0x7
	PR_GET_NAME                      = 0x10
	PR_GET_PDEATHSIG                 = 0x2
	PR_GET_SECCOMP                   = 0x15
	PR_GET_SECUREBITS                = 0x1b
	PR_GET_TIMERSLACK                = 0x1e
	PR_GET_TIMING                    = 0xd
	PR_GET_TSC                       = 0x19
	PR_GET_UNALIGN                   = 0x5
	PR_MCE_KILL                      = 0x21
	PR_MCE_KILL_CLEAR                = 0x0
	PR_MCE_KILL_DEFAULT              = 0x2
	PR_MCE_KILL_EARLY                = 0x1
	PR_MCE_KILL_GET                  = 0x22
	PR_MCE_KILL_LATE                 = 0x0
	PR_MCE_KILL_SET                  = 0x1
	PR_SET_DUMPABLE                  = 0x4
	PR_SET_ENDIAN                    = 0x14
	PR_SET_FPEMU                     = 0xa
	PR_SET_FPEXC                     = 0xc
	PR_SET_KEEPCAPS                  = 0x8
	PR_SET_NAME                      = 0xf
	PR_SET_PDEATHSIG                 = 0x1
	PR_SET_PTRACER                   = 0x59616d61
	PR_SET_SECCOMP                   = 0x16
	PR_SET_SECUREBITS                = 0x1c
	PR_SET_TIMERSLACK                = 0x1d
	PR_SET_TIMING                    = 0xe
	PR_SET_TSC                       = 0x1a
	PR_SET_UNALIGN                   = 0x6
	PR_TASK_PERF_EVENTS_DISABLE      = 0x1f
	PR_TASK_PERF_EVENTS_ENABLE       = 0x20
	PR_TIMING_STATISTICAL            = 0x0
	PR_TIMING_TIMESTAMP              = 0x1
	PR_TSC_ENABLE                    = 0x1
	PR_TSC_SIGSEGV                   = 0x2
	PR_UNALIGN_NOPRINT               = 0x1
	PR_UNALIGN_SIGBUS                = 0x2
	PTRACE_ATTACH                    = 0x10
	PTRACE_CONT                      = 0x7
	PTRACE_DETACH                    = 0x11
	PTRACE_EVENT_CLONE               = 0x3
	PTRACE_EVENT_EXEC                = 0x4
	PTRACE_EVENT_EXIT                = 0x6
	PTRACE_EVENT_FORK                = 0x1
	PTRACE_EVENT_VFORK               = 0x2
	PTRACE_EVENT_VFORK_DONE          = 0x5
	PTRACE_GETEVENTMSG               = 0x4201
	PTRACE_GETFPREGS                 = 0xe
	PTRACE_GETFPXREGS                = 0x12
	PTRACE_GETREGS                   = 0xc
	PTRACE_GETREGSET                 = 0x4204
	PTRACE_GETSIGINFO                = 0x4202
	PTRACE_GET_THREAD_AREA           = 0x19
	PTRACE_KILL                      = 0x8
	PTRACE_OLDSETOPTIONS             = 0x15
	PTRACE_O_MASK                    = 0x7f
	PTRACE_O_TRACECLONE              = 0x8
	PTRACE_O_TRACEEXEC               = 0x10
	PTRACE_O_TRACEEXIT               = 0x40
	PTRACE_O_TRACEFORK               = 0x2
	PTRACE_O_TRACESYSGOOD            = 0x1
	PTRACE_O_TRACEVFORK              = 0x4
	PTRACE_O_TRACEVFORKDONE          = 0x20
	PTRACE_PEEKDATA                  = 0x2
	PTRACE_PEEKTEXT                  = 0x1
	PTRACE_PEEKUSR                   = 0x3
	PTRACE_POKEDATA                  = 0x5
	PTRACE_POKETEXT                  = 0x4
	PTRACE_POKEUSR                   = 0x6
	PTRACE_SETFPREGS                 = 0xf
	PTRACE_SETFPXREGS                = 0x13
	PTRACE_SETOPTIONS                = 0x4200
	PTRACE_SETREGS                   = 0xd
	PTRACE_SETREGSET                 = 0x4205
	PTRACE_SETSIGINFO                = 0x4203
	PTRACE_SET_THREAD_AREA           = 0x1a
	PTRACE_SINGLEBLOCK               = 0x21
	PTRACE_SINGLESTEP                = 0x9
	PTRACE_SYSCALL                   = 0x18
	PTRACE_SYSEMU                    = 0x1f
	PTRACE_SYSEMU_SINGLESTEP         = 0x20
	PTRACE_TRACEME                   = 0x0
	RLIMIT_AS                        = _RLIMIT_AS
	RLIMIT_CORE                      = _RLIMIT_CORE
	RLIMIT_CPU                       = _RLIMIT_CPU
	RLIMIT_DATA                      = _RLIMIT_DATA
	RLIMIT_FSIZE                     = _RLIMIT_FSIZE
	RLIMIT_NOFILE                    = _RLIMIT_NOFILE
	RLIMIT_STACK                     = _RLIMIT_STACK
	RLIM_INFINITY                    = _RLIM_INFINITY
	RTAX_ADVMSS                      = 0x8
	RTAX_CWND                        = 0x7
	RTAX_FEATURES                    = 0xc
	RTAX_FEATURE_ALLFRAG             = 0x8
	RTAX_FEATURE_ECN                 = 0x1
	RTAX_FEATURE_SACK                = 0x2
	RTAX_FEATURE_TIMESTAMP           = 0x4
	RTAX_HOPLIMIT                    = 0xa
	RTAX_INITCWND                    = 0xb
	RTAX_INITRWND                    = 0xe
	RTAX_LOCK                        = 0x1
	RTAX_MAX                         = 0xe
	RTAX_MTU                         = 0x2
	RTAX_REORDERING                  = 0x9
	RTAX_RTO_MIN                     = 0xd
	RTAX_RTT                         = 0x4
	RTAX_RTTVAR                      = 0x5
	RTAX_SSTHRESH                    = 0x6
	RTAX_UNSPEC                      = 0x0
	RTAX_WINDOW                      = 0x3
	RTA_ALIGNTO                      = 0x4
	RTA_MAX                          = 0x10
	RTCF_DIRECTSRC                   = 0x4000000
	RTCF_DOREDIRECT                  = 0x1000000
	RTCF_LOG                         = 0x2000000
	RTCF_MASQ                        = 0x400000
	RTCF_NAT                         = 0x800000
	RTCF_VALVE                       = 0x200000
	RTF_ADDRCLASSMASK                = 0xf8000000
	RTF_ADDRCONF                     = 0x40000
	RTF_ALLONLINK                    = 0x20000
	RTF_BROADCAST                    = 0x10000000
	RTF_CACHE                        = 0x1000000
	RTF_DEFAULT                      = 0x10000
	RTF_DYNAMIC                      = 0x10
	RTF_FLOW                         = 0x2000000
	RTF_GATEWAY                      = 0x2
	RTF_HOST                         = 0x4
	RTF_INTERFACE                    = 0x40000000
	RTF_IRTT                         = 0x100
	RTF_LINKRT                       = 0x100000
	RTF_LOCAL                        = 0x80000000
	RTF_MODIFIED                     = 0x20
	RTF_MSS                          = 0x40
	RTF_MTU                          = 0x40
	RTF_MULTICAST                    = 0x20000000
	RTF_NAT                          = 0x8000000
	RTF_NOFORWARD                    = 0x1000
	RTF_NONEXTHOP                    = 0x200000
	RTF_NOPMTUDISC                   = 0x4000
	RTF_POLICY                       = 0x4000000
	RTF_REINSTATE                    = 0x8
	RTF_REJECT                       = 0x200
	RTF_STATIC                       = 0x400
	RTF_THROW                        = 0x2000
	RTF_UP                           = 0x1
	RTF_WINDOW                       = 0x80
	RTF_XRESOLVE                     = 0x800
	RTM_BASE                         = 0x10
	RTM_DELACTION                    = 0x31
	RTM_DELADDR                      = 0x15
	RTM_DELADDRLABEL                 = 0x49
	RTM_DELLINK                      = 0x11
	RTM_DELNEIGH                     = 0x1d
	RTM_DELQDISC                     = 0x25
	RTM_DELROUTE                     = 0x19
	RTM_DELRULE                      = 0x21
	RTM_DELTCLASS                    = 0x29
	RTM_DELTFILTER                   = 0x2d
	RTM_F_CLONED                     = 0x200
	RTM_F_EQUALIZE                   = 0x400
	RTM_F_NOTIFY                     = 0x100
	RTM_F_PREFIX                     = 0x800
	RTM_GETACTION                    = 0x32
	RTM_GETADDR                      = 0x16
	RTM_GETADDRLABEL                 = 0x4a
	RTM_GETANYCAST                   = 0x3e
	RTM_GETDCB                       = 0x4e
	RTM_GETLINK                      = 0x12
	RTM_GETMULTICAST                 = 0x3a
	RTM_GETNEIGH                     = 0x1e
	RTM_GETNEIGHTBL                  = 0x42
	RTM_GETQDISC                     = 0x26
	RTM_GETROUTE                     = 0x1a
	RTM_GETRULE                      = 0x22
	RTM_GETTCLASS                    = 0x2a
	RTM_GETTFILTER                   = 0x2e
	RTM_MAX                          = 0x4f
	RTM_NEWACTION                    = 0x30
	RTM_NEWADDR                      = 0x14
	RTM_NEWADDRLABEL                 = 0x48
	RTM_NEWLINK                      = 0x10
	RTM_NEWNDUSEROPT                 = 0x44
	RTM_NEWNEIGH                     = 0x1c
	RTM_NEWNEIGHTBL                  = 0x40
	RTM_NEWPREFIX                    = 0x34
	RTM_NEWQDISC                     = 0x24
	RTM_NEWROUTE                     = 0x18
	RTM_NEWRULE                      = 0x20
	RTM_NEWTCLASS                    = 0x28
	RTM_NEWTFILTER                   = 0x2c
	RTM_NR_FAMILIES                  = 0x10
	RTM_NR_MSGTYPES                  = 0x40
	RTM_SETDCB                       = 0x4f
	RTM_SETLINK                      = 0x13
	RTM_SETNEIGHTBL                  = 0x43
	RTNH_ALIGNTO                     = 0x4
	RTNH_F_DEAD                      = 0x1
	RTNH_F_ONLINK                    = 0x4
	RTNH_F_PERVASIVE                 = 0x2
	RTN_MAX                          = 0xb
	RTPROT_BIRD                      = 0xc
	RTPROT_BOOT                      = 0x3
	RTPROT_DHCP                      = 0x10
	RTPROT_DNROUTED                  = 0xd
	RTPROT_GATED                     = 0x8
	RTPROT_KERNEL                    = 0x2
	RTPROT_MRT                       = 0xa
	RTPROT_NTK                       = 0xf
	RTPROT_RA                        = 0x9
	RTPROT_REDIRECT                  = 0x1
	RTPROT_STATIC                    = 0x4
	RTPROT_UNSPEC                    = 0x0
	RTPROT_XORP                      = 0xe
	RTPROT_ZEBRA                     = 0xb
	RT_CLASS_DEFAULT                 = 0xfd
	RT_CLASS_LOCAL                   = 0xff
	RT_CLASS_MAIN                    = 0xfe
	RT_CLASS_MAX                     = 0xff
	RT_CLASS_UNSPEC                  = 0x0
	RUSAGE_CHILDREN                  = _RUSAGE_CHILDREN
	RUSAGE_SELF                      = _RUSAGE_SELF
	RUSAGE_THREAD                    = 0x1
	SCM_CREDENTIALS                  = 0x2
	SCM_RIGHTS                       = _SCM_RIGHTS
	SCM_TIMESTAMP                    = _SCM_TIMESTAMP
	SCM_TIMESTAMPING                 = 0x25
	SCM_TIMESTAMPNS                  = 0x23
	SHUT_RD                          = _SHUT_RD
	SHUT_RDWR                        = _SHUT_RDWR
	SHUT_WR                          = _SHUT_WR
	SIOCADDDLCI                      = 0x8980
	SIOCADDMULTI                     = 0x8931
	SIOCADDRT                        = 0x890b
	SIOCATMARK                       = 0x8905
	SIOCDARP                         = 0x8953
	SIOCDELDLCI                      = 0x8981
	SIOCDELMULTI                     = 0x8932
	SIOCDELRT                        = 0x890c
	SIOCDEVPRIVATE                   = 0x89f0
	SIOCDIFADDR                      = 0x8936
	SIOCDRARP                        = 0x8960
	SIOCGARP                         = 0x8954
	SIOCGIFADDR                      = 0xc08401a1
	SIOCGIFBR                        = 0x8940
	SIOCGIFBRDADDR                   = 0xc08401a3
	SIOCGIFCONF                      = 0xf00801a4
	SIOCGIFCOUNT                     = 0x8938
	SIOCGIFDSTADDR                   = 0xc08401a2
	SIOCGIFENCAP                     = 0x8925
	SIOCGIFFLAGS                     = 0xc4804191
	SIOCGIFHWADDR                    = 0xc08401a7
	SIOCGIFINDEX                     = 0xc88041da
	SIOCGIFMAP                       = 0x8970
	SIOCGIFMEM                       = 0x891f
	SIOCGIFMETRIC                    = 0x891d
	SIOCGIFMTU                       = 0xc88041b3
	SIOCGIFNAME                      = 0xc88041db
	SIOCGIFNETMASK                   = 0xc08401a5
	SIOCGIFPFLAGS                    = 0x8935
	SIOCGIFSLAVE                     = 0x8929
	SIOCGIFTXQLEN                    = 0x8942
	SIOCGPGRP                        = 0x8904
	SIOCGRARP                        = 0x8961
	SIOCGSTAMP                       = 0x8906
	SIOCGSTAMPNS                     = 0x8907
	SIOCPROTOPRIVATE                 = 0x89e0
	SIOCRTMSG                        = 0x890d
	SIOCSARP                         = 0x8955
	SIOCSIFADDR                      = 0x8084018c
	SIOCSIFBR                        = 0x8941
	SIOCSIFBRDADDR                   = 0x80840193
	SIOCSIFDSTADDR                   = 0x8918
	SIOCSIFENCAP                     = 0x8926
	SIOCSIFFLAGS                     = 0x84804190
	SIOCSIFHWADDR                    = 0x8924
	SIOCSIFHWBROADCAST               = 0x8937
	SIOCSIFLINK                      = 0x8911
	SIOCSIFMAP                       = 0x8971
	SIOCSIFMEM                       = 0x8920
	SIOCSIFMETRIC                    = 0x891e
	SIOCSIFMTU                       = 0x888041b4
	SIOCSIFNAME                      = 0x8923
	SIOCSIFNETMASK                   = 0x80840196
	SIOCSIFPFLAGS                    = 0x8934
	SIOCSIFSLAVE                     = 0x8930
	SIOCSIFTXQLEN                    = 0x8943
	SIOCSPGRP                        = 0x8902
	SIOCSRARP                        = 0x8962
	SOCK_CLOEXEC                     = _SOCK_CLOEXEC
	SOCK_DCCP                        = 0x6
	SOCK_DGRAM                       = _SOCK_DGRAM
	SOCK_NONBLOCK                    = _SOCK_NONBLOCK
	SOCK_PACKET                      = 0xa
	SOCK_RAW                         = _SOCK_RAW
	SOCK_RDM                         = _SOCK_RDM
	SOCK_SEQPACKET                   = _SOCK_SEQPACKET
	SOCK_STREAM                      = _SOCK_STREAM
	SOL_AAL                          = 0x109
	SOL_ATM                          = 0x108
	SOL_DECNET                       = 0x105
	SOL_ICMPV6                       = _SOL_ICMPV6
	SOL_IP                           = _SOL_IP
	SOL_IPV6                         = _SOL_IPV6
	SOL_IRDA                         = 0x10a
	SOL_PACKET                       = 0x107
	SOL_RAW                          = 0xff
	SOL_SOCKET                       = _SOL_SOCKET
	SOL_TCP                          = _SOL_TCP
	SOL_X25                          = 0x106
	SOMAXCONN                        = _SOMAXCONN
	SO_ACCEPTCONN                    = _SO_ACCEPTCONN
	SO_ATTACH_FILTER                 = 0x1a
	SO_BINDTODEVICE                  = 0x19
	SO_BROADCAST                     = _SO_BROADCAST
	SO_BSDCOMPAT                     = 0xe
	SO_DEBUG                         = _SO_DEBUG
	SO_DETACH_FILTER                 = 0x1b
	SO_DOMAIN                        = 0x27
	SO_DONTROUTE                     = _SO_DONTROUTE
	SO_ERROR                         = _SO_ERROR
	SO_KEEPALIVE                     = _SO_KEEPALIVE
	SO_LINGER                        = _SO_LINGER
	SO_MARK                          = 0x24
	SO_NO_CHECK                      = 0xb
	SO_OOBINLINE                     = _SO_OOBINLINE
	SO_PASSCRED                      = 0x10
	SO_PASSSEC                       = 0x22
	SO_PEERCRED                      = 0x11
	SO_PEERNAME                      = 0x1c
	SO_PEERSEC                       = 0x1f
	SO_PRIORITY                      = 0xc
	SO_PROTOCOL                      = 0x26
	SO_RCVBUF                        = _SO_RCVBUF
	SO_RCVBUFFORCE                   = 0x21
	SO_RCVLOWAT                      = _SO_RCVLOWAT
	SO_RCVTIMEO                      = _SO_RCVTIMEO
	SO_REUSEADDR                     = _SO_REUSEADDR
	SO_RXQ_OVFL                      = 0x28
	SO_SECURITY_AUTHENTICATION       = 0x16
	SO_SECURITY_ENCRYPTION_NETWORK   = 0x18
	SO_SECURITY_ENCRYPTION_TRANSPORT = 0x17
	SO_SNDBUF                        = _SO_SNDBUF
	SO_SNDBUFFORCE                   = 0x20
	SO_SNDLOWAT                      = _SO_SNDLOWAT
	SO_SNDTIMEO                      = _SO_SNDTIMEO
	SO_TIMESTAMP                     = _SO_TIMESTAMP
	SO_TIMESTAMPING                  = 0x25
	SO_TIMESTAMPNS                   = 0x23
	SO_TYPE                          = _SO_TYPE
	S_BLKSIZE                        = _S_BLKSIZE
	S_IEXEC                          = _S_IEXEC
	S_IFBLK                          = _S_IFBLK
	S_IFCHR                          = _S_IFCHR
	S_IFDIR                          = _S_IFDIR
	S_IFIFO                          = _S_IFIFO
	S_IFLNK                          = _S_IFLNK
	S_IFMT                           = _S_IFMT
	S_IFREG                          = _S_IFREG
	S_IFSOCK                         = _S_IFSOCK
	S_IREAD                          = _S_IREAD
	S_IRGRP                          = _S_IRGRP
	S_IROTH                          = _S_IROTH
	S_IRUSR                          = _S_IRUSR
	S_IRWXG                          = _S_IRWXG
	S_IRWXO                          = _S_IRWXO
	S_IRWXU                          = _S_IRWXU
	S_ISGID                          = _S_ISGID
	S_ISUID                          = _S_ISUID
	S_ISVTX                          = _S_ISVTX
	S_IWGRP                          = _S_IWGRP
	S_IWOTH                          = _S_IWOTH
	S_IWRITE                         = _S_IWRITE
	S_IWUSR                          = _S_IWUSR
	S_IXGRP                          = _S_IXGRP
	S_IXOTH                          = _S_IXOTH
	S_IXUSR                          = _S_IXUSR
	TCIFLUSH                         = _TCIFLUSH
	TCIOFLUSH                        = _TCIOFLUSH
	TCOFLUSH                         = _TCOFLUSH
	TCP_CONGESTION                   = _TCP_CONGESTION
	TCP_CORK                         = _TCP_CORK
	TCP_DEFER_ACCEPT                 = _TCP_DEFER_ACCEPT
	TCP_INFO                         = _TCP_INFO
	TCP_KEEPCNT                      = _TCP_KEEPCNT
	TCP_KEEPIDLE                     = _TCP_KEEPIDLE
	TCP_KEEPINTVL                    = _TCP_KEEPINTVL
	TCP_LINGER2                      = _TCP_LINGER2
	TCP_MAXSEG                       = _TCP_MAXSEG
	TCP_MAXWIN                       = _TCP_MAXWIN
	TCP_MAX_WINSHIFT                 = _TCP_MAX_WINSHIFT
	TCP_MD5SIG                       = _TCP_MD5SIG
	TCP_MD5SIG_MAXKEYLEN             = _TCP_MD5SIG_MAXKEYLEN
	TCP_MSS                          = _TCP_MSS
	TCP_NODELAY                      = _TCP_NODELAY
	TCP_QUICKACK                     = _TCP_QUICKACK
	TCP_SYNCNT                       = _TCP_SYNCNT
	TCP_WINDOW_CLAMP                 = _TCP_WINDOW_CLAMP
	TIOCCBRK                         = 0x5428
	TIOCCONS                         = 0x541d
	TIOCEXCL                         = 0x540c
	TIOCGDEV                         = 0x80045432
	TIOCGETD                         = 0x5424
	TIOCGICOUNT                      = 0x545d
	TIOCGLCKTRMIOS                   = 0x5456
	TIOCGPGRP                        = 0x60080777
	TIOCGPTN                         = 0x80045430
	TIOCGRS485                       = 0x542e
	TIOCGSERIAL                      = 0x541e
	TIOCGSID                         = 0x5429
	TIOCGSOFTCAR                     = 0x5419
	TIOCGWINSZ                       = 0x50200768
	TIOCINQ                          = 0x541b
	TIOCLINUX                        = 0x541c
	TIOCMBIC                         = 0x5417
	TIOCMBIS                         = 0x5416
	TIOCMGET                         = 0x6008076a
	TIOCMIWAIT                       = 0x545c
	TIOCMSET                         = 0xa008076d
	TIOCM_CAR                        = _TIOCM_CAR
	TIOCM_CD                         = _TIOCM_CD
	TIOCM_CTS                        = _TIOCM_CTS
	TIOCM_DSR                        = _TIOCM_DSR
	TIOCM_DTR                        = _TIOCM_DTR
	TIOCM_LE                         = _TIOCM_LE
	TIOCM_RI                         = _TIOCM_RI
	TIOCM_RNG                        = _TIOCM_RNG
	TIOCM_RTS                        = _TIOCM_RTS
	TIOCM_SR                         = _TIOCM_SR
	TIOCM_ST                         = _TIOCM_ST
	TIOCNOTTY                        = 0x771
	TIOCNXCL                         = 0x540d
	TIOCOUTQ                         = 0x5411
	TIOCPKT                          = 0x5420
	TIOCPKT_DATA                     = _TIOCPKT_DATA
	TIOCPKT_DOSTOP                   = _TIOCPKT_DOSTOP
	TIOCPKT_FLUSHREAD                = _TIOCPKT_FLUSHREAD
	TIOCPKT_FLUSHWRITE               = _TIOCPKT_FLUSHWRITE
	TIOCPKT_IOCTL                    = _TIOCPKT_IOCTL
	TIOCPKT_NOSTOP                   = _TIOCPKT_NOSTOP
	TIOCPKT_START                    = _TIOCPKT_START
	TIOCPKT_STOP                     = _TIOCPKT_STOP
	TIOCSBRK                         = 0x5427
	TIOCSCTTY                        = 0x761
	TIOCSERCONFIG                    = 0x5453
	TIOCSERGETLSR                    = 0x5459
	TIOCSERGETMULTI                  = 0x545a
	TIOCSERGSTRUCT                   = 0x5458
	TIOCSERGWILD                     = 0x5454
	TIOCSERSETMULTI                  = 0x545b
	TIOCSERSWILD                     = 0x5455
	TIOCSER_TEMT                     = 0x1
	TIOCSETD                         = 0x5423
	TIOCSIG                          = 0x40045436
	TIOCSLCKTRMIOS                   = 0x5457
	TIOCSPGRP                        = 0xa0080776
	TIOCSPTLCK                       = 0x40045431
	TIOCSRS485                       = 0x542f
	TIOCSSERIAL                      = 0x541f
	TIOCSSOFTCAR                     = 0x541a
	TIOCSTI                          = 0x5412
	TIOCSWINSZ                       = 0x90200767
	TUNATTACHFILTER                  = 0x400854d5
	TUNDETACHFILTER                  = 0x400854d6
	TUNGETFEATURES                   = 0x800454cf
	TUNGETIFF                        = 0x800454d2
	TUNGETSNDBUF                     = 0x800454d3
	TUNGETVNETHDRSZ                  = 0x800454d7
	TUNSETDEBUG                      = 0x400454c9
	TUNSETGROUP                      = 0x400454ce
	TUNSETIFF                        = 0x400454ca
	TUNSETLINK                       = 0x400454cd
	TUNSETNOCSUM                     = 0x400454c8
	TUNSETOFFLOAD                    = 0x400454d0
	TUNSETOWNER                      = 0x400454cc
	TUNSETPERSIST                    = 0x400454cb
	TUNSETSNDBUF                     = 0x400454d4
	TUNSETTXFILTER                   = 0x400454d1
	TUNSETVNETHDRSZ                  = 0x400454d8
	WALL                             = 0x40000000
	WCLONE                           = 0x80000000
	WCONTINUED                       = _WCONTINUED
	WEXITED                          = _WEXITED
	WNOHANG                          = _WNOHANG
	WNOTHREAD                        = 0x20000000
	WNOWAIT                          = _WNOWAIT
	WORDSIZE                         = 0x20
	WSTOPPED                         = _WSTOPPED
	WUNTRACED                        = _WUNTRACED
	FIOASYNC                         = 0xa008007d
	FIOGETOWN                        = 0x6008007b
	FIONBIO                          = 0xa008007e
	FIONREAD                         = 0x6008007f
	FIOSETOWN                        = 0xa008007c
	TIOCGETA                         = 0x62251713
	TIOCSETA                         = 0xa2251714
	TIOCSETAF                        = 0xa2251716
	TIOCSETAW                        = 0xa2251715
)

const (
	E2BIG           = Errno(0x40000007)
	EACCES          = Errno(0x4000000d)
	EADDRINUSE      = Errno(0x40000030)
	EADDRNOTAVAIL   = Errno(0x40000031)
	EADV            = Errno(0x44)
	EAFNOSUPPORT    = Errno(0x4000002f)
	EAGAIN          = Errno(0x40000023)
	EALREADY        = Errno(0x40000025)
	EBADE           = Errno(0x34)
	EBADF           = Errno(0x40000009)
	EBADFD          = Errno(0x4d)
	EBADMSG         = Errno(0x4000006b)
	EBADR           = Errno(0x35)
	EBADRQC         = Errno(0x38)
	EBADSLT         = Errno(0x39)
	EBFONT          = Errno(0x3b)
	EBUSY           = Errno(0x40000010)
	ECANCELED       = Errno(0x40000077)
	ECHILD          = Errno(0x4000000a)
	ECHRNG          = Errno(0x2c)
	ECOMM           = Errno(0x46)
	ECONNABORTED    = Errno(0x40000035)
	ECONNREFUSED    = Errno(0x4000003d)
	ECONNRESET      = Errno(0x40000036)
	EDEADLK         = Errno(0x4000000b)
	EDEADLOCK       = Errno(0x23)
	EDESTADDRREQ    = Errno(0x40000027)
	EDOM            = Errno(0x40000021)
	EDOTDOT         = Errno(0x49)
	EDQUOT          = Errno(0x40000045)
	EEXIST          = Errno(0x40000011)
	EFAULT          = Errno(0x4000000e)
	EFBIG           = Errno(0x4000001b)
	EHOSTDOWN       = Errno(0x40000040)
	EHOSTUNREACH    = Errno(0x40000041)
	EIDRM           = Errno(0x4000006c)
	EILSEQ          = Errno(0x4000006a)
	EINPROGRESS     = Errno(0x40000024)
	EINTR           = Errno(0x40000004)
	EINVAL          = Errno(0x40000016)
	EIO             = Errno(0x40000005)
	EISCONN         = Errno(0x40000038)
	EISDIR          = Errno(0x40000015)
	EISNAM          = Errno(0x78)
	EKEYEXPIRED     = Errno(0x7f)
	EKEYREJECTED    = Errno(0x81)
	EKEYREVOKED     = Errno(0x80)
	EL2HLT          = Errno(0x33)
	EL2NSYNC        = Errno(0x2d)
	EL3HLT          = Errno(0x2e)
	EL3RST          = Errno(0x2f)
	ELIBACC         = Errno(0x4f)
	ELIBBAD         = Errno(0x50)
	ELIBEXEC        = Errno(0x40000053)
	ELIBMAX         = Errno(0x52)
	ELIBSCN         = Errno(0x51)
	ELNRNG          = Errno(0x30)
	ELOOP           = Errno(0x4000003e)
	EMEDIUMTYPE     = Errno(0x7c)
	EMFILE          = Errno(0x40000018)
	EMLINK          = Errno(0x4000001f)
	EMSGSIZE        = Errno(0x40000028)
	EMULTIHOP       = Errno(0x4000006d)
	ENAMETOOLONG    = Errno(0x4000003f)
	ENAVAIL         = Errno(0x77)
	ENETDOWN        = Errno(0x40000032)
	ENETRESET       = Errno(0x40000034)
	ENETUNREACH     = Errno(0x40000033)
	ENFILE          = Errno(0x40000017)
	ENOANO          = Errno(0x37)
	ENOBUFS         = Errno(0x40000037)
	ENOCSI          = Errno(0x32)
	ENODATA         = Errno(0x4000006e)
	ENODEV          = Errno(0x40000013)
	ENOENT          = Errno(0x40000002)
	ENOEXEC         = Errno(0x40000008)
	ENOKEY          = Errno(0x7e)
	ENOLCK          = Errno(0x4000004d)
	ENOLINK         = Errno(0x4000006f)
	ENOMEDIUM       = Errno(0x7b)
	ENOMEM          = Errno(0x4000000c)
	ENOMSG          = Errno(0x40000070)
	ENONET          = Errno(0x40)
	ENOPKG          = Errno(0x41)
	ENOPROTOOPT     = Errno(0x4000002a)
	ENOSPC          = Errno(0x4000001c)
	ENOSR           = Errno(0x40000071)
	ENOSTR          = Errno(0x40000072)
	ENOSYS          = Errno(0x4000004e)
	ENOTBLK         = Errno(0x4000000f)
	ENOTCONN        = Errno(0x40000039)
	ENOTDIR         = Errno(0x40000014)
	ENOTEMPTY       = Errno(0x40000042)
	ENOTNAM         = Errno(0x76)
	ENOTRECOVERABLE = Errno(0x40000079)
	ENOTSOCK        = Errno(0x40000026)
	ENOTSUP         = Errno(0x40000076)
	ENOTTY          = Errno(0x40000019)
	ENOTUNIQ        = Errno(0x4c)
	ENXIO           = Errno(0x40000006)
	EOPNOTSUPP      = Errno(0x4000002d)
	EOVERFLOW       = Errno(0x40000073)
	EOWNERDEAD      = Errno(0x40000078)
	EPERM           = Errno(0x40000001)
	EPFNOSUPPORT    = Errno(0x4000002e)
	EPIPE           = Errno(0x40000020)
	EPROTO          = Errno(0x40000074)
	EPROTONOSUPPORT = Errno(0x4000002b)
	EPROTOTYPE      = Errno(0x40000029)
	ERANGE          = Errno(0x40000022)
	EREMCHG         = Errno(0x4e)
	EREMOTE         = Errno(0x40000047)
	EREMOTEIO       = Errno(0x79)
	ERESTART        = Errno(0x55)
	ERFKILL         = Errno(0x84)
	EROFS           = Errno(0x4000001e)
	ESHUTDOWN       = Errno(0x4000003a)
	ESOCKTNOSUPPORT = Errno(0x4000002c)
	ESPIPE          = Errno(0x4000001d)
	ESRCH           = Errno(0x40000003)
	ESRMNT          = Errno(0x45)
	ESTALE          = Errno(0x40000046)
	ESTRPIPE        = Errno(0x56)
	ETIME           = Errno(0x40000075)
	ETIMEDOUT       = Errno(0x4000003c)
	ETOOMANYREFS    = Errno(0x4000003b)
	ETXTBSY         = Errno(0x4000001a)
	EUCLEAN         = Errno(0x75)
	EUNATCH         = Errno(0x31)
	EUSERS          = Errno(0x40000044)
	EWOULDBLOCK     = Errno(0x40000023)
	EXDEV           = Errno(0x40000012)
	EXFULL          = Errno(0x36)
)

const (
	SIGABRT   = Signal(_SIGABRT)
	SIGALRM   = Signal(_SIGALRM)
	SIGBUS    = Signal(_SIGBUS)
	SIGCHLD   = Signal(_SIGCHLD)
	SIGCLD    = Signal(_SIGCLD)
	SIGCONT   = Signal(_SIGCONT)
	SIGFPE    = Signal(_SIGFPE)
	SIGHUP    = Signal(_SIGHUP)
	SIGILL    = Signal(_SIGILL)
	SIGINT    = Signal(_SIGINT)
	SIGIO     = Signal(_SIGIO)
	SIGIOT    = Signal(_SIGIOT)
	SIGKILL   = Signal(_SIGKILL)
	SIGPIPE   = Signal(_SIGPIPE)
	SIGPOLL   = Signal(_SIGPOLL)
	SIGPROF   = Signal(_SIGPROF)
	SIGPWR    = Signal(0x1e)
	SIGQUIT   = Signal(_SIGQUIT)
	SIGSEGV   = Signal(_SIGSEGV)
	SIGSTKFLT = Signal(0x10)
	SIGSTOP   = Signal(_SIGSTOP)
	SIGSYS    = Signal(_SIGSYS)
	SIGTERM   = Signal(_SIGTERM)
	SIGTRAP   = Signal(_SIGTRAP)
	SIGTSTP   = Signal(_SIGTSTP)
	SIGTTIN   = Signal(_SIGTTIN)
	SIGTTOU   = Signal(_SIGTTOU)
	SIGUNUSED = Signal(0x1f)
	SIGURG    = Signal(_SIGURG)
	SIGUSR1   = Signal(_SIGUSR1)
	SIGUSR2   = Signal(_SIGUSR2)
	SIGVTALRM = Signal(_SIGVTALRM)
	SIGWINCH  = Signal(_SIGWINCH)
	SIGXCPU   = Signal(_SIGXCPU)
	SIGXFSZ   = Signal(_SIGXFSZ)
)

// Error table
var errors = [...]string{
	1:   "Operation not permitted",
	2:   "No such file or directory",
	3:   "No such process",
	4:   "Interrupted system call",
	5:   "Input/output error",
	6:   "No such device or address",
	7:   "Argument list too long",
	8:   "Exec format error",
	9:   "Bad file descriptor",
	10:  "No child processes",
	11:  "Resource deadlock avoided",
	12:  "Cannot allocate memory",
	13:  "Permission denied",
	14:  "Bad address",
	15:  "Block device required",
	16:  "Device or resource busy",
	17:  "File exists",
	18:  "Invalid cross-device link",
	19:  "No such device",
	20:  "Not a directory",
	21:  "Is a directory",
	22:  "Invalid argument",
	23:  "Too many open files in system",
	24:  "Too many open files",
	25:  "Inappropriate ioctl for device",
	26:  "Text file busy",
	27:  "File too large",
	28:  "No space left on device",
	29:  "Illegal seek",
	30:  "Read-only file system",
	31:  "Too many links",
	32:  "Broken pipe",
	33:  "Numerical argument out of domain",
	34:  "Numerical result out of range",
	35:  "Resource temporarily unavailable",
	36:  "Operation now in progress",
	37:  "Operation already in progress",
	38:  "Socket operation on non-socket",
	39:  "Destination address required",
	40:  "Message too long",
	41:  "Protocol wrong type for socket",
	42:  "Protocol not available",
	43:  "Protocol not supported",
	44:  "Socket type not supported",
	45:  "Operation not supported",
	46:  "Protocol family not supported",
	47:  "Address family not supported by protocol",
	48:  "Address already in use",
	49:  "Cannot assign requested address",
	50:  "Network is down",
	51:  "Network is unreachable",
	52:  "Network dropped connection on reset",
	53:  "Software caused connection abort",
	54:  "Connection reset by peer",
	55:  "No buffer space available",
	56:  "Transport endpoint is already connected",
	57:  "Transport endpoint is not connected",
	58:  "Cannot send after transport endpoint shutdown",
	59:  "Too many references: cannot splice",
	60:  "Connection timed out",
	61:  "Connection refused",
	62:  "Too many levels of symbolic links",
	63:  "File name too long",
	64:  "Host is down",
	65:  "No route to host",
	66:  "Directory not empty",
	67:  "Too many processes",
	68:  "Too many users",
	69:  "Disk quota exceeded",
	70:  "Stale file handle",
	71:  "Object is remote",
	72:  "RPC struct is bad",
	73:  "RPC version wrong",
	74:  "RPC program not available",
	75:  "RPC program version wrong",
	76:  "RPC bad procedure for program",
	77:  "No locks available",
	78:  "Function not implemented",
	79:  "Inappropriate file type or format",
	80:  "Authentication error",
	81:  "Need authenticator",
	83:  "Cannot exec a shared library directly",
	100: "Inappropriate operation for background process",
	101: "Translator died",
	103: "You really blew it this time",
	104: "Computer bought the farm",
	105: "Gratuitous error",
	106: "Invalid or incomplete multibyte or wide character",
	107: "Bad message",
	108: "Identifier removed",
	109: "Multihop attempted",
	110: "No data available",
	111: "Link has been severed",
	112: "No message of desired type",
	113: "Out of streams resources",
	114: "Device not a stream",
	115: "Value too large for defined data type",
	116: "Protocol error",
	117: "Timer expired",
	118: "Not supported",
	119: "Operation canceled",
	120: "Owner died",
	121: "State not recoverable",
}

var signals = [...]string{
	1:  "Hangup",
	2:  "Interrupt",
	3:  "Quit",
	4:  "Illegal instruction",
	5:  "Trace/breakpoint trap",
	6:  "Aborted",
	7:  "EMT trap",
	8:  "Floating point exception",
	9:  "Killed",
	10: "Bus error",
	11: "Segmentation fault",
	12: "Bad system call",
	13: "Broken pipe",
	14: "Alarm clock",
	15: "Terminated",
	16: "Urgent I/O condition",
	17: "Stopped (signal)",
	18: "Stopped",
	19: "Continued",
	20: "Child exited",
	21: "Stopped (tty input)",
	22: "Stopped (tty output)",
	23: "I/O possible",
	24: "CPU time limit exceeded",
	25: "File size limit exceeded",
	26: "Virtual timer expired",
	27: "Profiling timer expired",
	28: "Window changed",
	29: "Information request",
	30: "User defined signal 1",
	31: "User defined signal 2",
	32: "Resource lost",
}
